### PR TITLE
Minor issues/typos in manual

### PR DESCRIPTION
**Pull request by m-schmidt**
I found some minor issues while reading the happy manual. This PR fixes them.

### CODE REVIEW

**Comment by erikd** [comment]
LGTM. Only thing I would suggest is to squash this into a single commit.

**Comment by m-schmidt** [comment]
Hm. Not sure whether my squashing worked.

**Comment by m-schmidt** [comment]
Will do a new PR

**Comment by erikd** [comment]
New PR is fine, but you should learn how to squash commits. Its well documented.

**Pull request closed without merging**
